---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fedora-silverblue-minimal
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: rpmfusion
    install:
      packages:
        - zsh
        - steam-devices
      exclude:
        - steam
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - gnome-software
        - malcontent-control
        - gnome-tour
        - htop
        - nvtop
        - adw-gtk3-theme
        - distrobox

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        title: Flathub (system)
        install: # system flatpaks we want all users to have and not remove
          - com.brave.Browser
          - com.mattjakeman.ExtensionManager
          - com.valvesoftware.Steam
          - io.github.kolunmi.Bazaar
          - org.gnome.TextEditor
          - org.gnome.Loupe
          - org.gnome.Weather
          - org.gnome.Calendar
          - org.gnome.Logs
          - org.gnome.Calculator
          - org.gnome.Papers
          - org.gnome.clocks
          - com.heroicgameslauncher.hgl
          - com.vysp3r.ProtonPlus

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
