---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: clean-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - zsh
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - gnome-software
        - malcontent-control
        - gnome-tour
        - htop
        - nvtop

  - type: default-flatpaks
    configurations:
      - scope: user
        # you can override the title to make inclusion of both system and user repos clearer
        title: Flathub (user)
      - notify: true
        scope: system
        title: Flathub (system)
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - io.missioncenter.MissionCenter
          - com.github.rafostar.Clapper
          - org.gnome.Loupe

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
